server:
  port: 5555

spring:
  application:
    name: notification-service

  rabbitmq:
    username: ersun
    password: ersun
    host: localhost
    port: 2222

  cloud:
    function:
      definition:
        sendNotification
    stream:
      rabbit:
        bindings:
          sendNotification-in-0:
            consumer:
              bindingRoutingKey: order-service-to-notification-service
          sendNotification-in-1:
            consumer:
              bindingRoutingKey: order-service-to-notification-service1
      bindings:
        sendNotification-in-0:
          destination: sira
          group: read-from-notification-queue
        sendNotification-in-1:
          destination: sira
          group: read-from-notification-queue1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:11111/eureka