server:
  port: 12345

spring:
  application:
    name: order-service

  rabbitmq:  # Burada rabbitmq ile ilgili konfigürasyonları giriyoruz. Host, port, kullanıcı adı ve şifre. Bağlantı kurmak için.
    username: ersun
    password: ersun
    port: 2222
    host: localhost

  cloud:
    stream:
      bindings:   # Binding dediğimiz şey exhange ile kuyruğun bağlanmasını konfigüre ettiğimiz bağ demek.
        output:   # Keyfi bir isim verdik. Fakat fonksiyonlarımızda kullandığımız StreamBridge içinde bu binding ile kuyruğa mesaj yazabiliriz.
          group: order-service-write-to-notification-queue    # Aynı kuyruğa birden fazla instance yazabilir. O nedenle aynı grub ismine sahip producerlar aynı kuyruğa ya da exchange'e yazabilirler.
          destination: sira   # Hedef exchange imizin adı.
      rabbit:
        bindings:
          output:
            producer:
              routingKeyExpression: "'order-service-to-notification-service'"

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:h2:mem:orderservicedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:11111/eureka