server:
  port: 2323

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders

eureka:
  client:
    service-url:
      defaultZone: http://localhost:11111/eureka